spring.application.name=core

server.port = 8080
spring.datasource.url=jdbc:h2:mem:corestock
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.config.import=optional:file:/config/kiwoom_api.yml

logging.level.root=WARN
logging.level.hello.coreStock=INFO
logging.level.com.zaxxer.hikari.pool.HikariPool=WARN

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}


stock.api.url=https://apis.data.go.kr/1160100/service/GetKrxListedInfoService/getItemPrice
stock.api.key_in=%2F%2FG4k9XO5XDw786gxL9NO1MCNstTlDuK9saP3cPuJ%2F2MLlmKmkNHHivxLE3eoT3%2B%2BrZqLw%2F8xIEmK8xwjUthWw%3D%3D
stock.api.key_de=//G4k9XO5XDw786gxL9NO1MCNstTlDuK9saP3cPuJ/2MLlmKmkNHHivxLE3eoT3++rZqLw/8xIEmK8xwjUthWw==