spring.application.name=core

server.port = 8080

spring.config.import=optional:file:/config/kiwoom_api.yml

logging.level.root=WARN
logging.level.hello.coreStock=INFO
logging.level.com.zaxxer.hikari.pool.HikariPool=WARN

cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:5173}